[build.lifecycle]
  onPreBuild = "git clone https://github.com/flutter/flutter.git -b stable && export PATH=\"$PATH:`pwd`/flutter/bin\""

[build]
  # Command Netlify runs to build your Flutter web app
  command = "bash ./install_flutter.sh && flutter build web"
  # The directory Netlify will serve as your website
  publish = "build/web"

[build.environment]
  # Flutter version (change this to your version)
  FLUTTER_VERSION = "3.24.3"

[[plugins]]
  # Ensures proper handling of single-page Flutter apps
  package = "@netlify/plugin-nextjs"

[[redirects]]
  # Redirects all routes to index.html (important for Flutter web routing)
  from = "/*"
  to = "/index.html"
  status = 200
