[build.lifecycle]
  onPreBuild = "git clone https://github.com/flutter/flutter.git -b stable && export PATH=\"$PATH:`pwd`/flutter/bin\""

[build]
  command = "bash ./install_flutter.sh && flutter build web"
  publish = "build/web"

[build.environment]
  FLUTTER_VERSION = "3.24.3"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

