[build]
  # Build command: install Flutter and build the web app
  command = "bash ./install_flutter.sh && export PATH=\"$PATH:`pwd`/flutter/bin\" && flutter build web"
  # Directory Netlify will serve
  publish = "build/web"

[[redirects]]
  # Flutter web routing: redirect all routes to index.html
  from = "/*"
  to = "/index.html"
  status = 200
